name = "workers-chat-demo"
main = "src/worker.mjs"
compatibility_date = "2024-09-22"

# Durable Objects
[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "limiters"
class_name = "RateLimiter"

# Durable Object migrations (required)
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]

# Optional: serve static assets (chat.html, chat.js, logo.png, etc.)
[assets]
directory = "src"
