name = "workers-chat-demo"
main = "src/worker.mjs"
compatibility_date = "2024-09-22"

# Durable Objects
[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "limiters"
class_name = "RateLimiter"

# Durable Object migrations (required)
[[migrations]]
tag = "v1"   # if you’ve already tried v1, change this to v2
new_sqlite_classes = ["ChatRoom", "RateLimiter"]

# Optional: serve static assets
[assets]
directory = "src"
