name = "workers-chat-demo"
main = "src/worker.mjs"
compatibility_date = "2024-09-22"

# Durable Objects
[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "limiters"
class_name = "RateLimiter"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom", "RateLimiter"]

# Serve React build
[assets]
directory = "chatapp/dist"
not_found_handling = "single-page-application"

